#!/bin/sh
#
# This file is generated by rules_gleam. DO NOT EDIT.

set -eu

PACKAGE={PACKAGE}
BASE=$(dirname $0)

run() {
  exec {ERL} \
    -pa "$BASE" \
    -eval "$PACKAGE@@main:run($PACKAGE)" \
    -noshell \
    -extra "$@"
}

run "$@"